### ISSUE TITLE
Support for yarn workspaces in monorepos with typescript

### ISSUE THREAD

**Issue by roderik** [nomiclabs/buidler#468]
In the typescript-support.ts file, there is some logic to determine if the typescript is supported by creating a list of all packages installed in ./node_modules and then seeing if they contain typescript and ts-node.

While using yarn workspaces, some dependencies might be in a node_modules folder higher in the directory structure. 

A workaround is to configure nohoist:

```
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/@nomiclabs/**",
      "**/typescript",
      "**/ts-node"
    ]
  },
```

But it would be better if the list of packages also included the packages higher up in the tree.

**Comment by alcuadrado** [comment]
Sorry we haven't got into this yet, @roderik. 

Do you think it would be ok if we use node's resolution to determine this? Instead of using actually looking into the `node_modules`, just run `require.resolve`.

**Comment by roderik** [comment]
Yes, I think that will work

**Comment by alcuadrado** [comment]
This was fixed and released in 1.4.5. Thanks for reporting it @roderik !

**Comment by kevupton** [comment]
I seem to still be getting this issue using hardhat v2.4.3

the nohoist value did not seem to fix it either.

This is the error I receive:
```
Error HH13: Your Hardhat project uses typescript, but ts-node is not installed.

Please run: npm `install --save-dev ts-node`
```

I an confirm ts-node is in the hardhat project node_modules as well

**Comment by alcuadrado** [comment]
Can you provide a way to reproduce it?

**Comment by aboutlo** [comment]
Hey @alcuadrado I had the same problem. 

I used:
- `yarn create eth-app my-eth-app` ( https://github.com/paulrberg/create-eth-app )
- `mkdir packages/hardhat-example`  
- `cd packages/hardhat-example`
- `npm install --save-dev hardhat`
- `npx hardhat` 

```
HH12: Hardhat is not installed or installed globally
```

`npx hardhat --version` > `2.6.7`

The above workaround worked

**Comment by alcuadrado** [comment]
@aboutlo you shouldn't mix yarn and npm, specially not with a monorepo. It will break things.

**Comment by aboutlo** [comment]
You are so right, I copy and paste without thinking! 🤦‍♂️ tks!
